# # builder
# FROM openjdk:11 AS builder
# COPY gradlew .
# COPY settings.gradle.kts .
# COPY build.gradle.kts .
# COPY gradle gradle
# COPY src src
# RUN chmod +x ./gradlew
# RUN ./gradlew bootJar


# deploy
FROM openjdk:11

ARG JAR_FILE
RUN mkdir /opt/app
COPY $JAR_FILE server.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "server.jar"]