# env
google-oauth2-client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
jwt-secret-key: ${JWT_SECRET_KEY}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USER}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    client-type: lettuce
    connect-timeout: 1m
  data:
    redis:
      repositories:
        enabled: false
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace
graphql:
  servlet:
    enabled: true
    mapping: /graphql
    exception-handlers-enabled: true
    cors:
      allowed-methods: GET, HEAD, POST
      allowed-origins: "*"
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
  tools:
    schema-location-pattern: "graphql/**/*.graphqls"
    # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
    # specification and expectations of most clients, so use this option with caution
    introspection-enabled: true
    use-default-objectmapper: true
  playground:
    mapping: /playground
    endpoint: /graphql
    subscriptionEndpoint: /subscriptions
    enabled: true
    pageTitle: Playground
    cdn:
      enabled: false
      version: latest
    settings:
      editor.fontFamily: "'Source Code Pro', 'Consolas', 'Inconsolata', 'Droid Sans Mono', 'Monaco', monospace"
      editor.fontSize: 14
      editor.reuseHeaders: true
      prettier.printWidth: 80
      prettier.tabWidth: 2
      prettier.useTabs: false
      schema.polling.enable: true
      schema.polling.endpointFilter: "*localhost*"
      schema.polling.interval: 2000
      schema.disableComments: true
      tracing.hideTracingResponse: true
  extended-scalars: Date, DateTime, Long
jwt:
  secret: ${jwt-secret-key}