# builder
FROM openjdk:11 AS builder
COPY gradlew .
COPY settings.gradle.kts .
COPY build.gradle.kts .
COPY gradle gradle
COPY src src
RUN chmod +x ./gradlew
RUN ./gradlew bootJar


# deploy
FROM openjdk:11
RUN mkdir /opt/app
COPY --from=builder build/libs/*.jar /opt/app/server.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/opt/app/server.jar"]