version: "3"

services:
  redis-message-queue:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always
  mysql-db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
      - ./scheme:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: adfaie83ma
    platform: linux/x86_64
